/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NFTMetadata = NftMetadataReference;
/**
 * Name of the item
 */
export type NftName = string;
/**
 * A human readable description of the item. Markdown is supported.
 */
export type NftDescription = string;
/**
 * This is the URL to the image of the item. Can be just about any type of image (including SVGs), and can be IPFS URLs or paths. The recommend size: 350px x 350px.
 */
export type NftImage = string;
/**
 * This is the URL that will appear below the asset's image on NFT markets or wallets and will allow users to get more information about the item on an external website.
 */
export type NftExternalUrl = string;
/**
 * Background color of the item on NFT markets, dashboards or other resources. Must be a six-character hexadecimal without a pre-pended #.
 */
export type NftBackgroundColor = string;
/**
 * A URL to a multi-media attachment for the item. The file extensions GLTF, GLB, WEBM, MP4, M4V, OGV, and OGG are supported, along with the audio-only extensions MP3, WAV, and OGA. Animation_url also supports HTML pages, allowing you to build rich experiences and interactive NFTs using JavaScript canvas, WebGL, and more. Scripts and relative paths within the HTML page are now supported. However, access to browser extensions is not supported.
 */
export type NftAnimationUrl = string;
/**
 * A field indicating how you would like trait attribute to be displayed
 */
export type NftAttributeTraitDisplayType = "number" | "boost_number" | "boost_percentage" | "date";
export type NftAttributes = NftAttributeReference[];

/**
 * ORGiD NFT Metadata Schema
 */
export interface NftMetadataReference {
  name: NftName;
  description: NftDescription;
  image: NftImage;
  external_url?: NftExternalUrl;
  background_color?: NftBackgroundColor;
  animation_url?: NftAnimationUrl;
  youtube_url?: NftAnimationUrl;
  attributes?: NftAttributes;
  [k: string]: unknown;
}
/**
 * Additional NFT Metadata attribute. This attributes format is adopting the OpenSea metadata recommendations: https://docs.opensea.io/docs/metadata-standards#attributes
 */
export interface NftAttributeReference {
  /**
   * The name of the trait
   */
  trait_type: string;
  /**
   * The trait value
   */
  value: string;
  display_type?: NftAttributeTraitDisplayType;
  [k: string]: unknown;
}
